package com.example.demo.repository;

import com.example.demo.model.PhoneBookModel;
import com.example.demo.model.PhoneBookModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhoneBookRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Thu Sep 17 17:45:59 JST 2020
     */
    long countByExample(PhoneBookModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Thu Sep 17 17:45:59 JST 2020
     */
    int deleteByExample(PhoneBookModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Thu Sep 17 17:45:59 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Thu Sep 17 17:45:59 JST 2020
     */
    int insert(PhoneBookModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Thu Sep 17 17:45:59 JST 2020
     */
    int insertSelective(PhoneBookModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Thu Sep 17 17:45:59 JST 2020
     */
    List<PhoneBookModel> selectByExample(PhoneBookModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Thu Sep 17 17:45:59 JST 2020
     */
    PhoneBookModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Thu Sep 17 17:45:59 JST 2020
     */
    int updateByExampleSelective(@Param("record") PhoneBookModel record, @Param("example") PhoneBookModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Thu Sep 17 17:45:59 JST 2020
     */
    int updateByExample(@Param("record") PhoneBookModel record, @Param("example") PhoneBookModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Thu Sep 17 17:45:59 JST 2020
     */
    int updateByPrimaryKeySelective(PhoneBookModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Thu Sep 17 17:45:59 JST 2020
     */
    int updateByPrimaryKey(PhoneBookModel record);
}